# Generated by Django 4.1.7 on 2023-03-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukaanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Clothing&Fashion', 'Clothing & Fashion'), ('Electronics', 'Electronics'), ('Home&Garden', 'Home & Garden'), ('Health&Beauty', 'Health & Beauty'), ('Sports&Outdoors', 'Sports & Outdoors'), ('Food&Beverage', 'Food & Beverage'), ('Toys&Games', 'Toys & Games'), ('Automotive', 'Automotive')], max_length=100, unique=True),
        ),
    ]
